### ISSUE TITLE
can the characther also rotate?

### ISSUE THREAD

**Issue by JohansenJunias20** [kvoeten/ExampleIK#1]
I really thank you for providing this video tutorial. your project is very helpful for me in doing my thesis,
Unfortunately for now I don't have a VR headset and I can't try this project.

Can the character rotate 180 degrees? For example, if I turn my body 180 degree,s does the character's body also rotate 180 degrees? does the unreal engine know that my "real" body is rotating?

**Comment by shirkan164** [comment]
If you watch the mirror closely while testing you will see that the character is rotating

**Comment by kvoeten** [comment]
I believe the implementation was setup to allow rotation once over a certain threshold (to not force the body to immediately align with the head, which often looks more natural; however the way this was done is not ideal and the body lags behind.).
